mscteachers/urls.py
# from django.conf import settings
# from django.conf.urls import include
# from django.contrib import admin
# from django.urls import path, re_path
# from django.views.generic import TemplateView

# from college import views




# urlpatterns = [
#     path('', views.home, name='home'),
#     path('admin/', admin.site.urls),
#     re_path(r'^.*export.*$', views.exportform),
#     re_path(r'^.*dumpteachers.*$', views.exportteachers, name='dumpteachers'),
#     re_path(r'^.*dumpexperts.*$', views.exportexperts, name='dumpexperts'),
#     re_path(r'^.*cloneyear.*$', views.cloneyear, name='cloneyear'),
#     re_path(r'^.*about.*$', TemplateView.as_view(template_name='admin/about.html'), name='aboutsystem'),
#     re_path(r'^.*docgen/', include(('thesis.urls', 'thesis'))),

# ]


# if settings.DEBUG:
#     import debug_toolbar

#     urlpatterns = [
#                       re_path(r'^__debug__/', include(debug_toolbar.urls)),
#                   ] + urlpatterns
from django.conf import settings
from django.conf.urls import include
from django.urls import path, re_path
from django.views.generic import TemplateView
from college import views
# Import your custom admin site instead of django.contrib.admin
from college.admin import admin_site  # Adjust the import path based on your file structure

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin_site.urls), 
    path('accounts/', include('django.contrib.auth.urls')), # Use your custom admin site
    
    re_path(r'^.*export.*$', views.exportform),
    re_path(r'^.*dumpteachers.*$', views.exportteachers, name='dumpteachers'),
    re_path(r'^.*dumpexperts.*$', views.exportexperts, name='dumpexperts'),
    re_path(r'^.*cloneyear.*$', views.cloneyear, name='cloneyear'),
    re_path(r'^.*about.*$', TemplateView.as_view(template_name='admin/about.html'), name='aboutsystem'),
    re_path(r'^.*docgen/', include(('thesis.urls', 'thesis'))),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

thesis/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('proposal_entries/', views.list_proposal_files, name='proposal_entries'),
    path('documents/proposal/<str:filename>/', views.serve_proposal_file, name='serve_proposal_file'),
    path('midTermNotice/', views.midTermNotice, name='midTermNotice'),
    path('proposalNotice/', views.proposalNotice, name='proposalNotice'),
    path('finalNotice/', views.finalNotice, name='finalNotice'),
    path('students/', views.students, name='students'),
    # path('supervisor/', views.supervisor, name='supervisor'),
    # path('examiner/', views.examiner, name='examiner'),
    path('midterm_entries/', views.list_midterm_files, name='midterm_entries'),
    path('documents/midterm/<str:filename>/', views.serve_midterm_file, name='serve_midterm_file'),
    path('final_entries/', views.list_final_files, name='final_entries'),  # Added this line
    path('documents/final/<str:filename>/', views.serve_final_file, name='serve_final_file'),  # Added this line
    path('mid_term_thesis_defense_list', views.midtermthesislist, name='mid_term_thesis_defense_list'),
    path('final_thesis_defense_list', views.finalthesislist, name='final_thesis_defense_list'),
    path('results', views.results, name='results'),
    # path('admin_setting', views.admin, name='admin_setting'),
    # path('budget', views.budget, name='budget'),
    path('invalid', views.invalid, name='invalid'),
]

college/models.py
import datetime

from django.db import models

# pw - dbms1234


Degree_Choices = {('PhD', 'PhD'), ('Masters', 'Masters'), ('Bachelors', 'Bachelors'), ('Diploma', 'Diploma')}
Semester_Choices = {('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth')}
Affiliation_Choices = {('Permanent', 'Permanent'), ('Contract', 'Contract'), ('Visiting', 'Visiting')}
Position_Choices = {('Prof Dr.', 'Prof Dr'), ('Dr.', 'Dr'), ('Mr.', 'Mr'), ('Ms.', 'Ms'), ('Mrs.', 'Mrs')}


class Programme(models.Model):
    name = models.CharField(max_length=50, unique=True )
    # coordinator, change to foreign key
    coordinator = models.ForeignKey(to='Teacher', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name


class Year(models.Model):
    name = models.CharField(max_length=40, default=str(int(datetime.date.today().strftime("%Y")) + 57) , unique=True )

    def __str__(self):
        return self.name


class Batch(models.Model):
    year = models.ForeignKey(Year, on_delete=models.CASCADE)
    programme = models.ForeignKey(Programme, on_delete=models.CASCADE)
    number_of_students = models.IntegerField(default='20')

    class Meta:
        unique_together = ("year", "programme")

    def __str__(self):
        return self.programme.name + ":" + self.year.name


class Semester(models.Model):
    semester_name = models.CharField(max_length=40, blank=True, null=True, unique=True, choices=Semester_Choices)

    def __str__(self):
        return self.semester_name


class HumanResource(models.Model):
    salutation = models.CharField(max_length=40, choices=Position_Choices, blank=True)
    first_name = models.CharField(max_length=40, )
    middle_name = models.CharField(max_length=40, blank=True)
    last_name = models.CharField(max_length=40, )
    mobile_phone = models.CharField(max_length=20, blank=True)
    home_phone = models.CharField(max_length=20, blank=True)
    email = models.EmailField(max_length=30, blank=True)
    upper_degree = models.CharField(max_length=30, choices=Degree_Choices, default='MSc')

    class Meta:
        abstract = True
        unique_together = ("first_name","last_name","mobile_phone", "upper_degree" )

    def full_name(self):
        return str(self.salutation + ' ' + self.first_name + ' ' + self.middle_name + ' ' + self.last_name)

    def __str__(self):
        return self.full_name()


class AffiliatedInstitute(models.Model):
    institute_name = models.CharField(max_length=50, unique=True)
    code = models.CharField(max_length=20)
    address = models.CharField(max_length=50, blank=True)
    office_phone = models.CharField(max_length=20, blank=True)
    office_email = models.CharField(max_length=20, blank=True)

    def __str__(self):
        return self.institute_name

    class Meta:
        verbose_name = "Organization / Affiliated Institutes"

class Teacher(HumanResource):
    teacher_id = models.CharField(max_length=20, blank=True, null=False)
    # known_subjects = models.ManyToManyField('Subject', null=True)
    aff_type = models.CharField(max_length=30, choices=Affiliation_Choices, default='Permanent')
    affiliated_institute = models.ForeignKey('AffiliatedInstitute', on_delete=models.CASCADE, null=True)
    started_teaching = models.CharField(verbose_name="started teaching in BS",  max_length=4, default=str(int(datetime.date.today().strftime("%Y")) + 57), blank=True)

    def get_known_subjects(self):
        return ",\n".join([p.name for p in self.known_subjects.all()])

    def get_teacher_id(self):
        return str(self.teacher_id)

    def get_teacher_experience_years(self):
        if self.started_teaching:
            return int(str(int(datetime.date.today().strftime("%Y")) + 57)) - int(self.started_teaching)
        else:
            return ""


class Subject(models.Model):
    name = models.CharField(max_length=40, blank=True, null=True, unique=True)
    elective = models.BooleanField(default=False)
    subject_code = models.CharField(max_length=40, blank=True, default=" ")
    # program = models.ForeignKey(Programme, on_delete=models.CASCADE, null=True)
    # semester = models.ForeignKey(Semester, on_delete=models.CASCADE)
    # subject_teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    credit = models.IntegerField(default="4")
    internal_marks = models.IntegerField(default="40")
    external_marks = models.IntegerField(default="60")

    # def total_marks(self):
    # return self.int_marks + self.ext_marks

    def __str__(self):
        return self.name


class AssignSubjectTeacher(models.Model):
    year = models.ForeignKey(Year, on_delete=models.CASCADE)
    batch = models.ForeignKey(Batch, on_delete=models.CASCADE)
    # programme = models.ForeignKey(Programme, on_delete=models.CASCADE)
    semester = models.CharField(max_length=40, choices=Semester_Choices)
    subject_teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    subject_teacher_teaching_experience_years = models.IntegerField(blank=True, default=0)

    class Meta:
        unique_together = ("year", "batch","subject", "subject_teacher", "semester" )
        verbose_name = "Subject Teacher Assignment"

    def programme(self):
        return self.batch.programme.name

    def getyearpart(self):
        if self.semester == "First":
            return "I/I"
        if self.semester == "Second":
            return "I/II"
        if self.semester == "Third":
            return "II/I"
        if self.semester == "Fourth":
            return "II/II"

    def part(self):
        if self.semester == 'First' or 'Third':
            return 'Odd'
        elif self.semester == 'Second' or 'Fourth':
            return 'Even'

    def __str__(self):
        return self.batch.year.name + " - " + self.batch.programme.name + self.semester + "  :  " + self.subject_teacher.first_name + " , " + self.subject.name


class Topic(models.Model):
    name = models.CharField(max_length=40, unique=True)

    def __str__(self):
        return self.name


class Expert(HumanResource):
    organization = models.ForeignKey('AffiliatedInstitute', on_delete=models.CASCADE, null=True)
    topic = models.ManyToManyField(Topic)

    def get_known_topics(self):
        return ",\n".join([p.name for p in self.topic.all()])

templates/coordinator/dashboard.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static 'admin/css/dashboard.css' %}">
{% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block content %}
<div id="content-main">
    <h1>Welcome, {{ coordinator.full_name }}</h1>

    <div class="module">
        <h2>My Programmes</h2>
        {% for programme in programmes %}
        <div class="programme-card">
            <h3>{{ programme.name }}</h3>
            <div class="programme-stats">
                <p>Total Batches: {{ programme.batch_set.count }}</p>
                <p>Current Teachers: {{ programme.assignsubjectteacher_set.count }}</p>
            </div>
            <div class="programme-actions">
                <a href="{% url 'college:manage_programme_teachers' programme.id %}" class="button">Manage Teachers</a>
                <a href="{% url 'college:view_programme_students' programme.id %}" class="button">View Students</a>
            </div>
        </div>
        {% empty %}
        <p>No programmes assigned yet.</p>
        {% endfor %}
    </div>

    <div class="module">
        <h2>Recent Subject Assignments</h2>
        <table>
            <thead>
                <tr>
                    <th>Subject</th>
                    <th>Teacher</th>
                    <th>Batch</th>
                    <th>Semester</th>
                </tr>
            </thead>
            <tbody>
                {% for assignment in subject_teachers|slice:":5" %}
                <tr>
                    <td>{{ assignment.subject.name }}</td>
                    <td>{{ assignment.subject_teacher.full_name }}</td>
                    <td>{{ assignment.batch }}</td>
                    <td>{{ assignment.semester }}</td>
                </tr>
                {% empty %}
                <tr><td colspan="4">No subject assignments yet.</td></tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

templates/coordinator/manage_programme.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block bodyclass %}{{ block.super }} manage-programme{% endblock %}

{% block content %}
<div id="content-main">
    <h1>{{ programme.name }} - Teacher Management</h1>

    <div class="module">
        <h2>Current Subject Teachers</h2>
        {% regroup subject_teachers by semester as semester_list %}
        
        {% for semester in semester_list %}
        <div class="semester-section">
            <h3>{{ semester.grouper }} Semester</h3>
            <table>
                <thead>
                    <tr>
                        <th>Subject</th>
                        <th>Teacher</th>
                        <th>Experience</th>
                        <th>Contact</th>
                    </tr>
                </thead>
                <tbody>
                    {% for assignment in semester.list %}
                    <tr>
                        <td>{{ assignment.subject.name }}</td>
                        <td>{{ assignment.subject_teacher.full_name }}</td>
                        <td>{{ assignment.subject_teacher_teaching_experience_years }} years</td>
                        <td>
                            {{ assignment.subject_teacher.email }}<br>
                            {{ assignment.subject_teacher.mobile_phone }}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% endfor %}
    </div>

    <div class="module">
        <h2>Quick Actions</h2>
        <div class="actions">
            <a href="{% url 'college:coordinator_export_form' %}" class="button">Export Teacher Data</a>
            <a href="{% url 'college:coordinator_dashboard' %}" class="button">Back to Dashboard</a>
        </div>
    </div>
</div>
{% endblock %}

templates/coordinator/view_students.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block bodyclass %}{{ block.super }} view-students{% endblock %}

{% block content %}
<div id="content-main">
    <h1>{{ programme.name }} - Student Overview</h1>

    <div class="module">
        <h2>Batches</h2>
        {% for batch in batches %}
        <div class="batch-section">
            <h3>Batch {{ batch.year.name }}</h3>
            <div class="batch-info">
                <p><strong>Number of Students:</strong> {{ batch.number_of_students }}</p>
                <p><strong>Current Semester:</strong> 
                    {% with batch.assignsubjectteacher_set.last as last_assignment %}
                        {% if last_assignment %}
                            {{ last_assignment.semester }}
                        {% else %}
                            Not assigned
                        {% endif %}
                    {% endwith %}
                </p>
            </div>
            
            <div class="semester-subjects">
                {% regroup batch.assignsubjectteacher_set.all by semester as semester_subjects %}
                {% for semester in semester_subjects %}
                <div class="semester-block">
                    <h4>{{ semester.grouper }} Semester</h4>
                    <ul>
                        {% for assignment in semester.list %}
                        <li>{{ assignment.subject.name }} - {{ assignment.subject_teacher.full_name }}</li>
                        {% endfor %}
                    </ul>
                </div>
                {% endfor %}
            </div>
        </div>
        {% empty %}
        <p>No batches found for this programme.</p>
        {% endfor %}
    </div>

    <div class="module">
        <h2>Actions</h2>
        <div class="actions">
            <a href="{% url 'college:manage_programme_teachers' programme.id %}" class="button">Manage Teachers</a>
            <a href="{% url 'college:coordinator_dashboard' %}" class="button">Back to Dashboard</a>
        </div>
    </div>
</div>
{% endblock %}